apiVersion: v1
kind: Service
metadata:
  name: ma7-mq-service
  labels:
    app: ma7-mq
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: ma7-mq-server
  type: ClusterIP
